#!/usr/bin/env bash
# 07-caddy.sh — 원격 VPS에 Caddy 설치 + 고객 도메인 2개 설정 (멱등)
#  {id}.{domain}        → localhost:3100  (프런트)
#  api.{id}.{domain}    → localhost:3101  (백엔드)
#
# TLS는 Let's Encrypt 자동 발급 (도메인이 VPS IP를 가리키고 있어야 함 — 00-dns 선행)

set -euo pipefail
: "${CUSTOMER_JSON:?}"

VPS_IP=$(jq -r '.vps.ip' "$CUSTOMER_JSON")
VPS_USER=$(jq -r '.vps.ssh_user // "root"' "$CUSTOMER_JSON")
VPS_PORT=$(jq -r '.vps.ssh_port // 22' "$CUSTOMER_JSON")

SUBDOMAIN=$(jq -r '.customer.id' "$CUSTOMER_JSON")
DOMAIN_SUFFIX=$(jq -r '.mail_server.domain // "teamver.online"' "$CUSTOMER_JSON")
FRONTEND_PORT=$(jq -r '.ports.frontend // 3100' "$CUSTOMER_JSON")
BACKEND_PORT=$(jq -r '.ports.backend // 3101' "$CUSTOMER_JSON")

FRONT_DOMAIN="${SUBDOMAIN}.${DOMAIN_SUFFIX}"
API_DOMAIN="api.${SUBDOMAIN}.${DOMAIN_SUFFIX}"

echo "• Caddy 설치·설정 (${FRONT_DOMAIN}, ${API_DOMAIN})"

ssh -p "$VPS_PORT" "${VPS_USER}@${VPS_IP}" 'bash -s' <<REMOTE
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

# 1. Caddy 설치 (이미 있으면 skip)
if ! command -v caddy >/dev/null 2>&1; then
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gnupg >/dev/null
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update -qq
  apt-get install -y -qq caddy
  echo "  Caddy 신규 설치"
else
  echo "  Caddy 이미 설치됨 (\$(caddy version | head -1))"
fi

# 2. Caddyfile 배치
cat > /etc/caddy/Caddyfile <<EOF
# Generated by deploy/lib/07-caddy.sh — ${FRONT_DOMAIN}
${FRONT_DOMAIN} {
    reverse_proxy localhost:${FRONTEND_PORT}
    encode gzip
}

${API_DOMAIN} {
    reverse_proxy localhost:${BACKEND_PORT}
    encode gzip
}
EOF

# 3. 검증 + reload
caddy validate --config /etc/caddy/Caddyfile >/dev/null
systemctl enable caddy >/dev/null 2>&1
systemctl reload caddy 2>/dev/null || systemctl restart caddy

sleep 2
if systemctl is-active --quiet caddy; then
  echo "  Caddy active"
else
  echo "  ❌ Caddy 활성화 실패"
  systemctl status caddy --no-pager 2>&1 | head -5
  exit 1
fi
REMOTE

# 외부에서 HTTPS 도달성 간이 확인 (TLS 발급 중일 수 있어 최대 60s 재시도)
echo "• HTTPS 도달성 폴링 (최대 60s, Let's Encrypt 초기 발급 시간 포함)"
for i in $(seq 1 20); do
  fc=$(curl -sk -o /dev/null -w "%{http_code}" -m 5 "https://${FRONT_DOMAIN}/" || echo 000)
  ac=$(curl -sk -o /dev/null -w "%{http_code}" -m 5 "https://${API_DOMAIN}/health" || echo 000)
  if [[ "$fc" =~ ^2 || "$fc" =~ ^3 ]] && [[ "$ac" == "200" ]]; then
    echo "  https://${FRONT_DOMAIN} → ${fc}, https://${API_DOMAIN}/health → ${ac}"
    break
  fi
  sleep 3
done

echo "✅ 07-caddy PASS"
